spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
# 在日志中显示实际执行的sql语句
logging:
  level:
    com.cskaoyan.basic.mybatisplus.mapper: debug