server:
  port: 8083
spring:
  main:
    web-application-type: reactive
  application:
    name: movieGateWay
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
          # nacos server地址
        server-addr: localhost:8848
    gateway:
      routes:
        - id: movieInfoService
          uri: lb://movieInfoService
          predicates:
            - Path=/movie/**
            - Method=GET
        - id: movieRatingService
          uri: lb://movieRatingService
          predicates:
            - Path=/rating/**
            - Method=GET

mybatis:
  type-aliases-package: com.cskaoyan.user.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
